version: '3.9'
services:
  tyk-dashboard:
    environment:
      - TYK_DB_STORAGE_MAIN_TYPE=mongo
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=mongodb://tyk-mongo:27017/tyk_analytics

  tyk-pump:
    env_file:
      - ./confs/pump.mongo.env
      
  tyk-mongo:
    image: mongo:4.0
    container_name: tyk-mongo

    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"

    volumes:
      - db-data:/data/db

    networks:
      - tyk

volumes:
  db-data:
